name: MobCapture
version: 1.2.6
author: WiseHollow
main: net.johnbrooks.mh.Main
api-version: '1.13'

softdepend: [ Vault, GriefPrevention, Towny ]

permissions:
  MobCapture.Admin:
    description: Performs administrative tasks regarding MobCapture.
    default: op
  MobCapture.Catch.*:
    description: Ability to capture all types of animals and monsters.
    default: op
  MobCapture.Catch.Peaceful:
    description: Ability to capture animals.
    default: op
  MobCapture.Catch.Hostile:
    description: Ability to capture monsters.
    default: op
  MobCapture.NoCost:
    description: Capture creatures without a cost.
    default: op

commands:
  MobCapture:
    description: Performs administrative tasks regarding MobCapture.
    usage: /<command> reload|update|version|spawn
    permission: MobCapture.admin
    permission-message: You don't have <permission>